name: Crawl and Save Data2

on:
  workflow_run:
    workflows: ["Crawl and Save Data1"]
    types:
      - completed

jobs:
  crawl_and_save:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas webdriver-manager selenium

    - name: Run crawling script
      run: python yotube_crawling-2.py  # 스크립트의 경로로 수정해주세요

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git pull origin main
        git add -A
        git commit -m "Update data [skip ci]"
    - name: Push changes
      run: |
        git push origin main    
